# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_products', '0002_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled')], max_length=1)),
                ('order_id', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=512)),
                ('product_url', models.CharField(max_length=1024)),
                ('cost_price', models.FloatField()),
            ],
        ),
    ]
