# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_products', '0004_auto_20170402_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
